# Generated by Django 3.1.2 on 2020-10-14 17:08

import budget.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'вид операции',
                'verbose_name_plural': 'виды операций',
                'default_related_name': 'kinds',
            },
            bases=(budget.models.mixins.AuthorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='вы можете указать свое название для расчета, либо просто укажите категорию', max_length=100, verbose_name='название расчета')),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='размер расчета')),
                ('type', models.IntegerField(choices=[(1, 'расход'), (2, 'доход')], default=1, verbose_name='тип расчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='budget.operationkind', verbose_name='вид расхода')),
            ],
            options={
                'verbose_name': 'операция',
                'verbose_name_plural': 'операции',
                'ordering': ['-created_at'],
                'default_related_name': 'operations',
            },
            bases=(budget.models.mixins.AuthorMixin, models.Model),
        ),
    ]
