# Generated by Django 3.1.2 on 2021-01-07 15:48

import budget.models.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20201108_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='size',
        ),
        migrations.AddField(
            model_name='operation',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата проведения'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.IntegerField(choices=[(1, 'расход'), (2, 'доход')], default=1, verbose_name='тип'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='budget.category')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'default_related_name': 'categories',
            },
            bases=(budget.models.mixins.AuthorMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='operation',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='budget.category', verbose_name='категория'),
        ),
        migrations.DeleteModel(
            name='OperationKind',
        ),
    ]
